feat: new homepage

diff --git a/.github/workflow/ci.yaml b/.github/workflow/ci.yaml
--- a/.github/workflow/ci.yaml
+++ b/.github/workflow/ci.yaml
@@ -1,40 +1,78 @@
-name: Node CI
+name: Publish to GitHub Pages
 
-on: [push, pull_request]
+on:
+  push:
+    branches: ['main']
+
+env:
+  NODE_AUTH_TOKEN: ${{ secrets.MY_HOMEPAGE}}
+
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+concurrency:
+  group: 'pages'
+  cancel-in-progress: true
+
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v1
+      - name: Checkout 🛎️
+        uses: actions/checkout@v3
+      - name: Detect package manager 👻
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node 🍉
+        uses: actions/setup-node@v3
         with:
-          node-version: 12.x
-      - run: yarn install
-      - run: yarn build
-      - name: Add artifact to github
-        uses: actions/upload-artifact@v2
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          node-version: '16.10.0'
+
+      - name: Setup Pages 🔧
+        id: pages
+        uses: actions/configure-pages@v1
         with:
-          name: artifact
-          path: build
-  gh-pages:
-    needs: [build]
-    name: gh-pages
-    runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main'
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v1
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: next
+      - name: Restore cache 💾
+        uses: actions/cache@v3
         with:
-          node-version: 12.x
-      - name: Download build
-        uses: actions/download-artifact@v2
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install dependencies 🥑
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js 🍄
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Static HTML export with Next.js 🥯
+        run: ${{ steps.detect-package-manager.outputs.runner }} next export
+      - name: Upload artifact ⛱️
+        uses: actions/upload-pages-artifact@v1
         with:
-          name: artifact
-          path: build
-      - name: rename folder
-        run: mv build docs && cp docs/index.html docs/404.html
-      - name: Deploy
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./docs # default: public
+          path: ./out
+
+  # Deployment job
